### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by akHawk** [sne3ks/Exode#1]
![image](https://cloud.githubusercontent.com/assets/23203690/19914155/3e67b794-a076-11e6-855e-86f109ba855a.png)

when running 'from Exode import *' i get this error. Help please!

**Comment by ln-nicolas** [comment]
Hello, 
which version of python do you use ? 

```
python3 --version / python -V
```

**Comment by JulesMichael** [comment]
Hey !
I think he use Python  2.7

**Comment by ln-nicolas** [comment]
Indeed, you're right .. I didn't see "Python27" in log messages. 
Exode is only available with Python3, you've to use Python3. 

Thanks to JulesMichael ;)

**Comment by akHawk** [comment]
Thanks!! I downloaded 2.7 earlier and didn't catch that 3 was the one I
needed.
