### ISSUE TITLE
File for installing core missing ?

### ISSUE THREAD

**Issue by steckhan** [sne3ks/Exode#3]
Hi, I'd like to try Exode, but where to find 

> ExodeArduinoCore\main\main.ino

which is needed to install the firmata ?

Best
Nico

**Comment by ln-nicolas** [comment]
Hello ! 
Sorry for the long delay, you'll found it by cloning this rep https://github.com/sne3ks/ExodeCore, in the examples folder 'basic.ino'.

You can also directly download ExodeCore through the Arduino IDE, here the installation guide : https://github.com/sne3ks/Exode/wiki/Installation-guide

Best,
