### ISSUE TITLE
No _winreg on windows 10 version 1703

### ISSUE THREAD

**Issue by ltheoret** [sne3ks/Exode#4]
Hi,

I am using Windows 10 Version 1703
I installed all components as listed in the Installation guide.
I have python ver. 3.6.3

here is the error:

[Exode_error.txt](https://github.com/sne3ks/Exode/files/1697688/Exode_error.txt)

Luc

**Comment by ltheoret** [comment]
hi,

Update:

removed the _ before winreg in Exode/Core/boardManager.py line 14
Still testing but so far so good.

Luc

**Comment by udaybm** [comment]
This works .I have configured my machine with conda and python and exode.
how to install and what to install on Arduino board.?

**Comment by ln-nicolas** [comment]
Hello, 
The installation guide is here [https://github.com/sne3ks/Exode/wiki/Installation-guide]( https://github.com/sne3ks/Exode/wiki/Installation-guide)

**Comment by udaybm** [comment]
Thanks..got everything installed with conda.. haven't yet uploaded basic.ino sketch..will give it a try soon...
Regards
Uday

**Comment by udaybm** [comment]
Hey one issue..
Could run some initial led example code on conda environment Terminal but not on Jupyter eg.
uno=BOARD.search() just hangs in jupyter.why?

**Comment by udaybm** [comment]
one more question:let me know an alternative to Kivy that is compatible with openGL1.1 version.My win8 Hard does not permit openGL to upgrade to 2.0+.

**Comment by udaybm** [comment]
Hello 
Everything is working fine ,only stuck up because my hardware doesn't support Open GL upgrade above v1.1 and Kivy requires openGL2.0 .So asking for a workaround or alternative for Kivy.
Regards
Uday.

**Comment by udaybm** [comment]
WxPython looks fine👍
